### ISSUE TITLE
Vizualization documentation

### ISSUE THREAD

**Issue by ToddRosenkrantz** [wenh06/fl-sim#4]
Could you provide a few lines of example documentation to produce the visualizations?
When I run 'python viz.py', I get errors, including '..node Node' cannot be imported.

This is from inside the container after running 'fl-sim example-configs/fedavg-femnist.yml'

Any assistance is appreciated.

**Comment by wenh06** [comment]
The [Panel](https://github.com/wenh06/fl-sim/blob/master/fl_sim/utils/viz.py#L447) class in this file is typically used in a [Jupyter notebook](https://jupyter.org/install). It requires [ipywidgets >= 8](https://ipywidgets.readthedocs.io/en/stable/) (perhaps needs nodejs installed).

It's highly recommended to [run a notebook server](https://jupyter-notebook.readthedocs.io/en/4.x/public_server.html) (has [updates](https://jupyter-server.readthedocs.io/en/latest/operators/migrate-from-nbserver.html) but not required) on some Linux (Ubuntu) machine via (for example)
```bash
nohup jupyter notebook --no-browser > ~/Jupyter/jupyter.log 2>&1 & echo $! > ~/Jupyter/jupyter.pid
```
and use this visualization Panel in a browser (e.g. Chrome, Edge, etc.).

**Comment by ToddRosenkrantz** [comment]
Thank you.  Your answer provided me enough information to reinstall, add Jupyter and subsequently provide graphical data.

**Comment by ToddRosenkrantz** [comment]
once Jupyter is installed:
in a new notebook, add two cells.

[1] from fl_sim.utils.viz import Panel
[2] p = Panel()

This issue should be considered closed.
